/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Persona_Rol;
import Tools.Excepciones;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JifChangePassword extends javax.swing.JInternalFrame {

    private DAO_Persona_Rol objPersonaRolData;
    private Excepciones objExcepciones;
    private String password, DNI;
    private int rol;

    /**
     * Creates new form JifChangePassword
     */
    public JifChangePassword() {
        initComponents();
        this.objExcepciones = new Excepciones();
        this.password = "";
        this.DNI = "";
        this.rol = 0;
        //String password = new String(jPasswordFieldContraseña.getPassword());
    }

    public JifChangePassword(String password, String DNI, int rol) {
        try {
            initComponents();
            this.objExcepciones = new Excepciones();
            this.password = password;
            this.DNI = DNI;
            this.rol = rol;
            this.objPersonaRolData = new DAO_Persona_Rol();
            //String password = new String(jPasswordFieldContraseña.getPassword());
        } catch (SQLException ex) {
            System.out.println("Data cambiar password error: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PWFNuevaPass = new javax.swing.JPasswordField();
        BtnNuevaPass = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel1.setText("Nueva contraseña: ");

        PWFNuevaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWFNuevaPassActionPerformed(evt);
            }
        });
        PWFNuevaPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PWFNuevaPassKeyReleased(evt);
            }
        });

        BtnNuevaPass.setText("Cambiar");
        BtnNuevaPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevaPassActionPerformed(evt);
            }
        });

        jLabel4.setText("* La contraseña debe tener: ");

        jLabel5.setText("1. Entre 8 y 16 caracteres");

        jLabel6.setText("2. Al menos un dígito, una mayuscula y una minuscula.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PWFNuevaPass, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(BtnNuevaPass)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(PWFNuevaPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnNuevaPass))
                .addGap(11, 11, 11)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevaPassActionPerformed

        this.changePass();

    }//GEN-LAST:event_BtnNuevaPassActionPerformed

    private void PWFNuevaPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWFNuevaPassActionPerformed
        this.changePass();
    }//GEN-LAST:event_PWFNuevaPassActionPerformed

    private void PWFNuevaPassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PWFNuevaPassKeyReleased
        this.objExcepciones.validarExpresionTxt(this.PWFNuevaPass, "^(?=\\w*\\d)(?=\\w*[A-Z])(?=\\w*[a-z])\\S{8,16}$");
    }//GEN-LAST:event_PWFNuevaPassKeyReleased

    private void changePass() {
        try {
            if (!this.PWFNuevaPass.getText().equals("") && this.PWFNuevaPass.getForeground() != Color.RED) {
                if (this.objPersonaRolData.changePassword(this.PWFNuevaPass.getText(), this.DNI, this.rol)) {
                    JOptionPane.showMessageDialog(this, "Cambio de contraseña exitoso.", "Cambiar Contraseña", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Lo siento, no puede dehar el campo vacio.", "Cambiar Contraseña", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JifChangePassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnNuevaPass;
    private javax.swing.JPasswordField PWFNuevaPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
