/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author MARCELO RUENES
 */
public class JifConsultaPersona extends javax.swing.JInternalFrame {

    JifListar_Personas obJifListar_Personas;
    String idPersonaSeleccionada;
    String nombrePersonaSeleccionada;
    String telefonoPersonaSeleccionada;
    String fechaRegPersonaSeleccionada;
    String direccionPersonaSeleccionada;
    String nacimientoPersonaSeleccionada;

    /**
     * Creates new form JifConsutaPersona
     */
    public JifConsultaPersona() {
        initComponents();

        this.idPersonaSeleccionada = "";
        this.nombrePersonaSeleccionada = "";
        this.telefonoPersonaSeleccionada = "";
        this.fechaRegPersonaSeleccionada = "";
        this.direccionPersonaSeleccionada = "";
        this.nacimientoPersonaSeleccionada = "";

        this.idPersonaSeleccionada = JifListar_Personas.idPersonaSeleccionada;
        this.nombrePersonaSeleccionada = JifListar_Personas.nacimientoPersonaSeleccionada;
        this.telefonoPersonaSeleccionada = JifListar_Personas.telefonoPersonaSeleccionada;
        this.fechaRegPersonaSeleccionada = JifListar_Personas.fechaRegPersonaSeleccionada;
        this.direccionPersonaSeleccionada = JifListar_Personas.direccionPersonaSeleccionada;
        this.nacimientoPersonaSeleccionada = JifListar_Personas.nacimientoPersonaSeleccionada;

        this.LblNombre.setText("NOMBRE: " + this.nombrePersonaSeleccionada);
        this.LblDni.setText("IDENTIFICACIÓN: " + this.idPersonaSeleccionada);
        this.LblTelefono.setText("TELEFONO: " + this.telefonoPersonaSeleccionada);
        this.LblFechaReg.setText("FECHA DE REGISTRO: " + this.fechaRegPersonaSeleccionada);
        this.LblDireccion.setText("DIRECCIÓN: " + this.direccionPersonaSeleccionada);
        this.LblFechaNac.setText("FECHA DE NACIMIENTO: " + this.idPersonaSeleccionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LblDireccion = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        LblTelefono = new javax.swing.JLabel();
        LblDni = new javax.swing.JLabel();
        BtnAceptar = new javax.swing.JButton();
        LblFechaReg = new javax.swing.JLabel();
        LblFechaNac = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("DETALLE DE PERSONA:");

        LblDireccion.setText("DIRECCION: ");

        LblNombre.setText("NOMBRE:");

        LblTelefono.setText("TELEFONO:");

        LblDni.setText("IDENTIFICACION:");

        BtnAceptar.setText("ACEPTAR");
        BtnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAceptarActionPerformed(evt);
            }
        });

        LblFechaReg.setText("FECHA DE REGISTRO:");

        LblFechaNac.setText("FECHA DE NACIMIENTO:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNombre)
                            .addComponent(LblTelefono)
                            .addComponent(LblDni)
                            .addComponent(LblFechaReg)
                            .addComponent(LblDireccion)
                            .addComponent(LblFechaNac)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(BtnAceptar)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(LblNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LblTelefono)
                .addGap(18, 18, 18)
                .addComponent(LblFechaReg)
                .addGap(18, 18, 18)
                .addComponent(LblDireccion)
                .addGap(18, 18, 18)
                .addComponent(LblFechaNac)
                .addGap(18, 18, 18)
                .addComponent(BtnAceptar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(139, 139, 139))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAceptarActionPerformed
        this.obJifListar_Personas = new JifListar_Personas();
        this.obJifListar_Personas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAceptarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAceptar;
    private javax.swing.JLabel LblDireccion;
    private javax.swing.JLabel LblDni;
    private javax.swing.JLabel LblFechaNac;
    private javax.swing.JLabel LblFechaReg;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblTelefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
