/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Persona;
import Controlador.DAO_Rol;
import Modelo.DTO_Persona;
import Modelo.DTO_Rol;
import Modelo.Excepciones;
import Modelo.TimestampCertificates;
import java.security.Timestamp;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MARCELO RUENES
 */
public class JifEmpleado extends javax.swing.JInternalFrame {

    private Excepciones objExcepciones;
    private DAO_Rol objDataRol;
    private DAO_Persona objDataPersona;

    /**
     * Creates new form JifEmpleado
     */
    public JifEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtIdEmp = new javax.swing.JTextField();
        TxtNombreEmp = new javax.swing.JTextField();
        TxtFechaNacEmp = new javax.swing.JTextField();
        TxtTelEmp = new javax.swing.JTextField();
        TxtDirEmp = new javax.swing.JTextField();
        BtnAgregarEmpleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cbx_Rol = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("AGREGAR PERSONA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Direcciión:");

        TxtIdEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TxtNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEmpActionPerformed(evt);
            }
        });

        TxtFechaNacEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        TxtTelEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtTelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelEmpActionPerformed(evt);
            }
        });

        TxtDirEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BtnAgregarEmpleado.setText("AGREGAR");
        BtnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ROL:");

        Cbx_Rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. EMPLEADO", "2. PROVEEDOR", "3. REPRESENTANTE LEGAL", "4. ADMINISTRADOR" }));
        Cbx_Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbx_RolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtDirEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(TxtTelEmp)
                            .addComponent(TxtFechaNacEmp)
                            .addComponent(TxtNombreEmp)
                            .addComponent(TxtIdEmp)
                            .addComponent(Cbx_Rol, 0, 1, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel1)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(BtnAgregarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cbx_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtFechaNacEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtDirEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarEmpleado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreEmpActionPerformed

    private void TxtTelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelEmpActionPerformed

    private void BtnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEmpleadoActionPerformed
        try {
            DAO_Persona objDataPersona = new DAO_Persona();
            TimestampCertificates tc = new TimestampCertificates();
            if (this.objExcepciones.validarCamposPersona(TxtIdEmp, TxtNombreEmp, TxtFechaNacEmp, TxtTelEmp, TxtDirEmp)
                    && this.objExcepciones.validarCamposErrPersona(TxtIdEmp, TxtNombreEmp, TxtFechaNacEmp, TxtTelEmp, TxtDirEmp)) {

                if (this.TxtIdEmp.isEnabled()) {
                    if (objDataPersona.registrarNuevaPersona(new DTO_Persona(this.TxtIdEmp.getText(),
                            this.TxtNombreEmp.getText().toUpperCase(),
                            this.getRolById(),
                            this.TxtTelEmp.getText(),
                            this.TxtDirEmp.getText(),
                            new Timestamp(new Date(), tc.getCertPath()),
                            this.TxtFechaNacEmp.getText()
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡La persona " + this.TxtNombreEmp.getText().toUpperCase() + " se ha registrado con éxito!", "Registro de producto", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Registro de persona", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    if (objDataPersona.modificarPersona(new DTO_Persona(this.TxtIdEmp.getText(),
                            this.TxtNombreEmp.getText().toUpperCase(),
                            this.getRolById(),
                            this.TxtFechaNacEmp.getText(),
                            this.TxtTelEmp.getText(),
                            new Timestamp(new Date(), tc.getCertPath()),
                            this.TxtDirEmp.getText()
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡La persona " + this.TxtNombreEmp.getText().toUpperCase() + " se ha modificado con éxito!", "Modificación de persona", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Modificación de persona", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }else {
                JOptionPane.showMessageDialog(this, "No puede dejar campos vacios o erroneos", "Registro de persona", JOptionPane.ERROR_MESSAGE);
           }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 0) {
                int res = JOptionPane.showConfirmDialog(this, "Esta persona ya se encuentra registrado\n"
                        + "¿Desea editarlo?", "Registro de persona", JOptionPane.ERROR_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {
                    try {
                        this.fillData(this.objDataPersona.getSinglePersona(this.TxtIdEmp.getText()));
                    } catch (SQLException exSP) {
                        Logger.getLogger(JifEmpleado.class.getName()).log(Level.SEVERE, null, exSP);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Registro de persona", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnAgregarEmpleadoActionPerformed

    private void Cbx_RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbx_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbx_RolActionPerformed

    private DTO_Rol getRolById() throws SQLException {
        String item = this.Cbx_Rol.getSelectedItem().toString();
        int id_Rol = Integer.parseInt(item.split("-")[0]);
        return this.objDataRol.getSingleRol(id_Rol);
    }

    private void cleanAllInputs() {
        this.TxtIdEmp.setText("");
        this.TxtIdEmp.setEnabled(true);
        this.TxtNombreEmp.setText("");
        this.TxtFechaNacEmp.setText("");
        this.TxtTelEmp.setText("");
        this.TxtDirEmp.setText("");
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarEmpleado;
    private javax.swing.JComboBox<String> Cbx_Rol;
    private javax.swing.JTextField TxtDirEmp;
    private javax.swing.JTextField TxtFechaNacEmp;
    private javax.swing.JTextField TxtIdEmp;
    private javax.swing.JTextField TxtNombreEmp;
    private javax.swing.JTextField TxtTelEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

private void fillData(DTO_Persona objProducto) {
        this.TxtIdEmp.setText(objProducto.getDNI());
        this.TxtNombreEmp.setText(objProducto.getNombre());
        this.Cbx_Rol.setSelectedItem(objProducto.getRol().getId_Rol()+ "- "
                + objProducto.getRol().getNombre_Rol());
        this.TxtTelEmp.setText(objProducto.getTelefono());
        this.TxtDirEmp.setText(objProducto.getDireccion());
        this.TxtFechaNacEmp.setText(objProducto.getFecha_Nacimiento());
        this.BtnAgregarEmpleado.setText("Modificar persona");
    
}
}
