/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Producto;
import Modelo.DTO_Producto;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JifFactura extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifFactura
     */
    private DTO_Producto objProducto;

    public JifFactura() {
        initComponents();
        this.objProducto = new DTO_Producto();
    }

    public JifFactura(String titulo) {
        initComponents();
        this.lblTitulo.setText(titulo);
        this.objProducto = new DTO_Producto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LblIdFactura = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaProductos = new javax.swing.JTextArea();
        TxtProducto = new javax.swing.JTextField();
        SpnCantidad = new javax.swing.JSpinner();
        BtnAgregar = new javax.swing.JButton();
        SpnFecha = new javax.swing.JSpinner();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblTitulo.setText("Título");

        jLabel1.setText("VENTA #");

        LblIdFactura.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LblIdFactura.setText("\"\"");
        LblIdFactura.setVerifyInputWhenFocusTarget(false);

        AreaProductos.setColumns(20);
        AreaProductos.setRows(5);
        jScrollPane1.setViewportView(AreaProductos);

        TxtProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtProductoActionPerformed(evt);
            }
        });

        SpnCantidad.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        BtnAgregar.setText("AGREGAR");

        SpnFecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        SpnFecha.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SpnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAgregar)
                .addGap(38, 38, 38))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LblIdFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(SpnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitulo)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(LblIdFactura)
                    .addComponent(SpnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAgregar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtProductoActionPerformed
        try {
            DAO_Producto objDataProducto = new DAO_Producto();
            this.AreaProductos.setEnabled(false);
            this.objProducto = objDataProducto.getSingleProducto(this.TxtProducto.getText());
            AreaProductos.append(this.objProducto.getNombre() + " | "
                    + (int)(this.objProducto.getPrecio_Compra() - (this.objProducto.getPorcentaje_Venta() * this.objProducto.getPrecio_Compra())));
            AreaProductos.append(System.getProperty("line.separator")); // Esto para el salto de línea 
            //JOptionPane.showMessageDialog(this, " " + this.TxtProducto.getText());

        } catch (SQLException ex) {
            Logger.getLogger(JifFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.TxtProducto.setText("");
    }//GEN-LAST:event_TxtProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaProductos;
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JLabel LblIdFactura;
    private javax.swing.JSpinner SpnCantidad;
    private javax.swing.JSpinner SpnFecha;
    private javax.swing.JTextField TxtProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
