/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Persona;
import Modelo.DTO_Persona;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCELO RUENES
 */
public class JifListar_Personas extends javax.swing.JInternalFrame {

    private final DefaultTableModel modelo;
    private DAO_Persona objDataPersona;
    private JifConsultaPersona objconsultaPersRol;
    private ArrayList<DTO_Persona> PersonList;
    private boolean current_state;
    public static String idPersonaSeleccionada;
    public static String nombrePersonaSeleccionada;
    public static String telefonoPersonaSeleccionada;
    public static String fechaRegPersonaSeleccionada;
    public static String direccionPersonaSeleccionada;
    public static String nacimientoPersonaSeleccionada;

    /**
     * Creates new form JifListarPersonas
     */
    public JifListar_Personas() {
        initComponents();
        this.current_state = true;
        this.objconsultaPersRol= new JifConsultaPersona();
        modelo = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        modelo.addColumn("Identificacion");
        modelo.addColumn("Nombre");
        modelo.addColumn("Telefono");
        modelo.addColumn("Fecha");
        modelo.addColumn("Direccion");
        modelo.addColumn("Fecha de nacimiento");

        try {
            this.objDataPersona = new DAO_Persona();
            this.PersonList = this.objDataPersona.getAllPersonas(this.current_state);
        } catch (SQLException ex) {
            System.out.println("Error: " + ex.getMessage());
        }

        this.Tbl_Personas.setModel(modelo);
        this.addRows();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Personas = new javax.swing.JTable();
        TxtBuscarNom = new javax.swing.JTextField();
        TxtBuscarcod = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        Tbl_Personas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tbl_Personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_PersonasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_Personas);

        TxtBuscarNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarNomActionPerformed(evt);
            }
        });
        TxtBuscarNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarNomKeyReleased(evt);
            }
        });

        TxtBuscarcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarcodActionPerformed(evt);
            }
        });
        TxtBuscarcod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtBuscarcodKeyReleased(evt);
            }
        });

        jLabel1.setText("Buscar por nombre:");

        jLabel2.setText("Buscar por identificacion:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Lista de personas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TxtBuscarNom, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(TxtBuscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtBuscarNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtBuscarcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtBuscarNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarNomActionPerformed
        search("nombre", this.TxtBuscarNom.getText().toUpperCase());
    }//GEN-LAST:event_TxtBuscarNomActionPerformed

    private void TxtBuscarcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarcodActionPerformed
        search("dni", this.TxtBuscarcod.getText().toUpperCase());
    }//GEN-LAST:event_TxtBuscarcodActionPerformed

    private void TxtBuscarNomKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarNomKeyReleased
        search("nombre", this.TxtBuscarNom.getText().toUpperCase());
    }//GEN-LAST:event_TxtBuscarNomKeyReleased

    private void TxtBuscarcodKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarcodKeyReleased
        search("dni", this.TxtBuscarcod.getText().toUpperCase());
    }//GEN-LAST:event_TxtBuscarcodKeyReleased

    private void Tbl_PersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_PersonasMouseClicked
        if (evt.getClickCount() == 2) {
            idPersonaSeleccionada= Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 0).toString();
            nombrePersonaSeleccionada= Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 1).toString();
            telefonoPersonaSeleccionada= Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 2).toString();
            fechaRegPersonaSeleccionada=Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 3).toString();
            direccionPersonaSeleccionada=Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 4).toString();
            nacimientoPersonaSeleccionada=Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 5).toString();
            this.objconsultaPersRol= new JifConsultaPersona();
            this.objconsultaPersRol.show();
        } else if   (evt.getClickCount() == 1) {
            this.objconsultaPersRol.setVisible(false);
        } 
    }//GEN-LAST:event_Tbl_PersonasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tbl_Personas;
    private javax.swing.JTextField TxtBuscarNom;
    private javax.swing.JTextField TxtBuscarcod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void addRows() {
        this.PersonList.forEach(Persona -> {
            this.modelo.addRow(new Object[]{
                Persona.getDNI(),
                Persona.getNombre(),
                Persona.getTelefono(),
                Persona.getFecha(),
                Persona.getDireccion(),
                Persona.getFecha_Nacimiento()});
        });
    }

    public String idFactura() {
        return this.Tbl_Personas.getValueAt(Tbl_Personas.getSelectedRow(), 0).toString();
    }

    private void search(String Atributo, String getTextBox) {
        try {
            this.PersonList.clear();
            for (int i = this.Tbl_Personas.getRowCount() - 1; i >= 0; i--) {
                this.modelo.removeRow(i);
            }
            this.PersonList = this.objDataPersona.getPersonasByQuery(Atributo,getTextBox, this.current_state);
            this.addRows();
        } catch (SQLException ex) {
            //Logger.getLogger(JifListar_Persona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
