/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Persona;
import Controlador.DAO_Persona_Rol;
import Controlador.DAO_Rol;
import Modelo.DTO_Persona_Rol;
import Modelo.DTO_Rol;
import Modelo.Excepciones;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JifLogin extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifLogin
     */
    private DAO_Rol objDataRol;
    private DAO_Persona_Rol objDataPersonaRol;
    private Excepciones objExcepciones;
    private DTO_Persona_Rol objPersona_Rol;

    public DTO_Persona_Rol getObjPersona_Rol() {
        return objPersona_Rol;
    }

    public JifLogin() {
        try {
            initComponents();
            this.objExcepciones = new Excepciones();
            this.objDataPersonaRol = new DAO_Persona_Rol();
            this.objDataRol = new DAO_Rol();
            this.objPersona_Rol = null;
            if (this.Cbx_Rol.getItemCount() <= 0) {
                this.Pnl_Rol.setVisible(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JifLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Rbg_Rol = new javax.swing.ButtonGroup();
        LblMainTitulo = new javax.swing.JLabel();
        Pnl_UserData = new javax.swing.JPanel();
        Txt_DNI = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PWF_Contrasena = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Pnl_Rol = new javax.swing.JPanel();
        Cbx_Rol = new javax.swing.JComboBox<>();
        Lbl_Rol = new javax.swing.JLabel();
        Btn_Ingresar = new javax.swing.JButton();

        LblMainTitulo.setText("Bienvenido al software de Distribelleza");

        Pnl_UserData.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del usuario"));

        Txt_DNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_DNIKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_DNIKeyReleased(evt);
            }
        });

        jLabel2.setText("Documento:");

        jLabel3.setText("Contraseña:");

        PWF_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWF_ContrasenaActionPerformed(evt);
            }
        });
        PWF_Contrasena.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PWF_ContrasenaKeyReleased(evt);
            }
        });

        jLabel4.setText("* La contraseña debe tener: ");

        jLabel5.setText("1. Entre 8 y 16 caracteres");

        jLabel6.setText("2. Al menos un dígito, una mayuscula y una minuscula.");

        javax.swing.GroupLayout Pnl_UserDataLayout = new javax.swing.GroupLayout(Pnl_UserData);
        Pnl_UserData.setLayout(Pnl_UserDataLayout);
        Pnl_UserDataLayout.setHorizontalGroup(
            Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_UserDataLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(Pnl_UserDataLayout.createSequentialGroup()
                        .addGroup(Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_DNI)
                            .addComponent(PWF_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pnl_UserDataLayout.setVerticalGroup(
            Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_UserDataLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_UserDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PWF_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6))
        );

        Pnl_Rol.setBorder(javax.swing.BorderFactory.createTitledBorder("Rol"));

        Lbl_Rol.setText("¿Como vas a ingresar hoy?");

        Btn_Ingresar.setText("Ingresar");
        Btn_Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_IngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_RolLayout = new javax.swing.GroupLayout(Pnl_Rol);
        Pnl_Rol.setLayout(Pnl_RolLayout);
        Pnl_RolLayout.setHorizontalGroup(
            Pnl_RolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_RolLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_Rol)
                .addGap(27, 27, 27)
                .addComponent(Cbx_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(Pnl_RolLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(Btn_Ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pnl_RolLayout.setVerticalGroup(
            Pnl_RolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_RolLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Pnl_RolLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cbx_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_Rol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Ingresar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(LblMainTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Pnl_UserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblMainTitulo)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pnl_UserData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pnl_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_IngresarActionPerformed
        try {
            if ((this.objPersona_Rol != null)) {
                this.objPersona_Rol.setRol(this.getRolById());
                if (this.objDataPersonaRol.setNewSession(this.objPersona_Rol)) {
                    this.setVisible(false);
                    this.setClosed(true);
                    JOptionPane.showMessageDialog(this,
                            "Bienvenido Sr(a) " + this.objPersona_Rol.getPersona().getNombre() + ".",
                            "Inicio exitoso",
                            JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (SQLException | PropertyVetoException ex) {
            Logger.getLogger(JifLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_IngresarActionPerformed

    private void PWF_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWF_ContrasenaActionPerformed

//Aqui buscamos en la BD
        if ((!this.Txt_DNI.getText().equals("") && this.PWF_Contrasena.getPassword().length > 0)
                && (!this.Txt_DNI.getForeground().equals(Color.red) && !this.PWF_Contrasena.getForeground().equals(Color.red))) {
            try {
                this.objPersona_Rol = this.objDataPersonaRol.getSessionPersona(this.Txt_DNI.getText(), this.PWF_Contrasena.getText().trim());
                if (this.objPersona_Rol != null) {
                    this.Pnl_Rol.setVisible(true);
                    this.Txt_DNI.setEnabled(false);
                    this.PWF_Contrasena.setEnabled(false);
                    this.objDataPersonaRol.getListOfRols(this.Txt_DNI.getText()).forEach(rol -> {
                        this.Cbx_Rol.addItem(rol.getId_Rol() + "- " + rol.getNombre_Rol());
                    });
                    this.LblMainTitulo.setText("Hola " + this.objPersona_Rol.getPersona().getNombre() + ", bienvenido a nuestro sistema.");
                } else {
                    JOptionPane.showMessageDialog(this, "Contraseña o usuario incorrecto", "Iniciar sesión", JOptionPane.WARNING_MESSAGE);
                }

            } catch (SQLException ex) {
                Logger.getLogger(JifLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No puedes dejar campos vacios o erroneo", "Iniciar sesión", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_PWF_ContrasenaActionPerformed

    private void Txt_DNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DNIKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_Txt_DNIKeyPressed

    private void Txt_DNIKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_DNIKeyReleased
        this.objExcepciones.validarExpresionTxt(this.Txt_DNI, "^(\\d{5,12})$");
    }//GEN-LAST:event_Txt_DNIKeyReleased

    private void PWF_ContrasenaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PWF_ContrasenaKeyReleased
        this.objExcepciones.validarExpresionTxt(this.PWF_Contrasena, "^(?=\\w*\\d)(?=\\w*[A-Z])(?=\\w*[a-z])\\S{8,16}$");
    }//GEN-LAST:event_PWF_ContrasenaKeyReleased

    private DTO_Rol getRolById() throws SQLException {
        String item = this.Cbx_Rol.getSelectedItem().toString();
        int id_Rol = Integer.parseInt(item.split("-")[0]);
        return this.objDataRol.getSingleRol(id_Rol, true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Ingresar;
    private javax.swing.JComboBox<String> Cbx_Rol;
    private javax.swing.JLabel LblMainTitulo;
    private javax.swing.JLabel Lbl_Rol;
    private javax.swing.JPasswordField PWF_Contrasena;
    private javax.swing.JPanel Pnl_Rol;
    private javax.swing.JPanel Pnl_UserData;
    private javax.swing.ButtonGroup Rbg_Rol;
    private javax.swing.JTextField Txt_DNI;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
