/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Categoria;
import Controlador.DAO_Categoria_Marca;
import Controlador.DAO_Marca;
import Controlador.DAO_Persona;
import Controlador.DAO_Producto;
import Modelo.DTO_Categoria;
import Modelo.DTO_Marca;
import Modelo.DTO_Persona;
import Modelo.DTO_Producto;
import Tools.Excepciones;
import Tools.TimestampCertificates;
import java.awt.Color;
import java.beans.PropertyVetoException;
import java.security.Timestamp;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class JifProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifProducto
     */
    private DAO_Categoria objDataCategoria;
    private DAO_Marca objDataMarca;
    private DAO_Persona objDataProveedor;
    private DAO_Producto objDataProducto;
    private DAO_Categoria_Marca objDataCategoria_Marca;
    private DTO_Categoria objCategoria;
    private DTO_Persona objProveedor;
    private DTO_Marca objMarca;
    private Excepciones objExcepciones;
    private DefaultTableModel tblCatModel;
    private DefaultTableModel tblMarcModel;
    private boolean current_state;

    public JifProducto() {
        initComponents();
        try {
            setComponentsCofig();
        } catch (SQLException ex) {
            System.out.println("Error en la Base de datos: " + ex.getMessage());
        }
    }

    public JifProducto(String Titulo) {
        initComponents();
        //System.out.println("Example: " + Tipo);
        this.lblTitulo.setText(Titulo);

        try {
            this.setComponentsCofig();
        } catch (SQLException ex) {
            System.out.println("Error en la Base de datos: " + ex.getMessage());
        }
    }

    public JifProducto(DTO_Producto objProducto, String Titulo) {
        initComponents();
        //System.out.println("Example: " + Tipo);
        this.lblTitulo.setText(Titulo);

        try {
            this.setComponentsCofig();
            this.fillProductData(objProducto);
        } catch (SQLException ex) {
            System.out.println("Error en la Base de datos: " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        JtpProducto = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cbx_Marca = new javax.swing.JComboBox<>();
        Cbx_Cat = new javax.swing.JComboBox<>();
        Txt_Id_Prod = new javax.swing.JTextField();
        Txt_Nombre = new javax.swing.JTextField();
        Spn_Precio_Compra = new javax.swing.JSpinner();
        Spn_Porcentaje_Venta = new javax.swing.JSpinner();
        Spn_Cantidad = new javax.swing.JSpinner();
        btn_RegistrarProd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Lbl_CatTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_Categoria = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Txt_Categoria = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Btn_AddCategoria = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        Btn_EliminarCat = new javax.swing.JButton();
        Btn_ModificarCat = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Lbl_TituloMarca = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tbl_Marca = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        Txt_Marca = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Cbx_Proveedor = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        Cbx_MarcaCat = new javax.swing.JComboBox<>();
        Btn_AddMarca = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        Btn_EliminarMarca = new javax.swing.JButton();
        Btn_EditMarca = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        TBN_EstadoCat = new javax.swing.JToggleButton();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblTitulo.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        lblTitulo.setText("Título");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del producto"));
        jPanel1.setToolTipText("");

        jLabel6.setText("Porcentaje de venta: ");

        jLabel1.setText("ID del Producto");

        jLabel2.setText("Marca:");

        jLabel3.setText("Categoría:");

        jLabel4.setText("Nombre/Referencia:");

        jLabel5.setText("Precio de compra:");

        jLabel7.setText("Cantidades existentes:");

        Txt_Id_Prod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_Id_ProdActionPerformed(evt);
            }
        });
        Txt_Id_Prod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_Id_ProdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_Id_ProdKeyReleased(evt);
            }
        });

        Txt_Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_NombreKeyReleased(evt);
            }
        });

        Spn_Precio_Compra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Spn_Precio_CompraKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Spn_Precio_CompraKeyReleased(evt);
            }
        });

        Spn_Porcentaje_Venta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Spn_Porcentaje_VentaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Spn_Porcentaje_VentaKeyReleased(evt);
            }
        });

        Spn_Cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Spn_CantidadKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Spn_CantidadKeyReleased(evt);
            }
        });

        btn_RegistrarProd.setText("Registrar Producto");
        btn_RegistrarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarProdActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        jButton1.setText("Ver lista de productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(Spn_Cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(54, 54, 54)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cbx_Marca, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Txt_Id_Prod)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Cbx_Cat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Txt_Nombre)
                                    .addComponent(Spn_Precio_Compra)
                                    .addComponent(Spn_Porcentaje_Venta))))
                        .addGap(69, 69, 69)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btn_RegistrarProd)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(Txt_Id_Prod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(Cbx_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Cbx_Cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Spn_Precio_Compra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Spn_Porcentaje_Venta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Spn_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_RegistrarProd)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        JtpProducto.addTab("Producto", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Categoria"));

        Lbl_CatTitulo.setText("Nueva categoria");

        jScrollPane1.setViewportView(Tbl_Categoria);

        jScrollPane2.setViewportView(jScrollPane1);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Categoría"));

        Txt_Categoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_CategoriaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_CategoriaKeyReleased(evt);
            }
        });

        jLabel8.setText("Nombre:");

        Btn_AddCategoria.setText("Agregar");
        Btn_AddCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_AddCategoria)
                    .addComponent(Txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(Txt_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_AddCategoria)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Categoría"));

        Btn_EliminarCat.setText("Eliminar");
        Btn_EliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarCatActionPerformed(evt);
            }
        });

        Btn_ModificarCat.setText("Modificar");
        Btn_ModificarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Btn_ModificarCat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(Btn_EliminarCat)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_EliminarCat)
                    .addComponent(Btn_ModificarCat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Lbl_CatTitulo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Lbl_CatTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        JtpProducto.addTab("Categorias", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la marca"));

        Lbl_TituloMarca.setText("Nueva marca");

        jScrollPane3.setViewportView(Tbl_Marca);

        jScrollPane4.setViewportView(jScrollPane3);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Marca"));

        Txt_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_MarcaActionPerformed(evt);
            }
        });
        Txt_Marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_MarcaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Txt_MarcaKeyReleased(evt);
            }
        });

        jLabel10.setText("Nombre:");

        jLabel11.setText("Proveedor");

        jLabel12.setText("Categoria");

        Btn_AddMarca.setText("Agregar");
        Btn_AddMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AddMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Marca)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Btn_AddMarca)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addComponent(Cbx_Proveedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cbx_MarcaCat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(Txt_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Cbx_Proveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(Cbx_MarcaCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Btn_AddMarca)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Administrar Marca"));

        Btn_EliminarMarca.setText("Eliminar");
        Btn_EliminarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarMarcaActionPerformed(evt);
            }
        });

        Btn_EditMarca.setText("Editar");
        Btn_EditMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EditMarcaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Btn_EditMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_EliminarMarca)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_EliminarMarca)
                    .addComponent(Btn_EditMarca))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(Lbl_TituloMarca))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(287, 287, 287))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(Lbl_TituloMarca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JtpProducto.addTab("Marca", jPanel3);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado"));

        TBN_EstadoCat.setText("Cambiar estado");
        TBN_EstadoCat.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TBN_EstadoCatItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TBN_EstadoCat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(TBN_EstadoCat)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(JtpProducto, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JtpProducto)
                .addContainerGap())
        );

        JtpProducto.getAccessibleContext().setAccessibleName("Producto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_Id_ProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_Id_ProdActionPerformed

    }//GEN-LAST:event_Txt_Id_ProdActionPerformed

    private void btn_RegistrarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarProdActionPerformed
        try {
            DAO_Producto objDataProducto = new DAO_Producto();
            TimestampCertificates tc = new TimestampCertificates();
            if (this.objExcepciones.validarCamposProducto(Txt_Id_Prod, Txt_Nombre, Spn_Precio_Compra, Spn_Cantidad, Spn_Porcentaje_Venta)
                    && this.objExcepciones.validarCamposErrProducto(Txt_Id_Prod, Txt_Nombre, Spn_Precio_Compra, Spn_Cantidad, Spn_Porcentaje_Venta)) {

                if (this.Txt_Id_Prod.isEnabled()) {
                    //@START: Nuevo Producto
                    if (objDataProducto.registrarNuevoProducto(new DTO_Producto(this.Txt_Id_Prod.getText(),
                            this.getMarcaById(),
                            this.getCategoryById(this.Cbx_Cat),
                            this.Txt_Nombre.getText().toUpperCase(),
                            Double.parseDouble(this.Spn_Precio_Compra.getValue().toString()),
                            (int) this.Spn_Cantidad.getValue(),
                            Double.parseDouble(this.Spn_Porcentaje_Venta.getValue().toString()) / 100,
                            new Timestamp(new Date(), tc.getCertPath()),
                            true
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡El producto " + this.Txt_Nombre.getText().toUpperCase() + " se ha registrado con éxito!", "Registro de producto", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Registro de producto", JOptionPane.ERROR_MESSAGE);
                    }
                    //@END: Nuevo Producto
                } else {
                    //@START: Editar Producto
                    if (objDataProducto.modificarProducto(new DTO_Producto(this.Txt_Id_Prod.getText(),
                            this.getMarcaById(),
                            this.getCategoryById(this.Cbx_Cat),
                            this.Txt_Nombre.getText().toUpperCase(),
                            Double.parseDouble(this.Spn_Precio_Compra.getValue().toString()),
                            (int) this.Spn_Cantidad.getValue(),
                            Double.parseDouble(this.Spn_Porcentaje_Venta.getValue().toString()) / 100,
                            new Timestamp(new Date(), tc.getCertPath())
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡El producto " + this.Txt_Nombre.getText().toUpperCase() + " se ha modificado con éxito!", "Modificación de producto", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Modificación de producto", JOptionPane.ERROR_MESSAGE);
                    }
                    //@END: Editar Producto
                }

            } else {
                JOptionPane.showMessageDialog(this, "No puede dejar campos vacios o erroneos", "Registro de producto", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 0) {
                int res = JOptionPane.showConfirmDialog(this, "El producto ya se encuentra registrado\n"
                        + "¿Desea editarlo?", "Registro de producto", JOptionPane.ERROR_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {
                    try {
                        this.fillProductData(this.objDataProducto.getSingleProducto(this.Txt_Id_Prod.getText(), true));
                    } catch (SQLException exSP) {
                        Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, exSP);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Registro de producto", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_RegistrarProdActionPerformed

    private void Txt_NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyPressed
        this.objExcepciones.validarLetra(evt);
    }//GEN-LAST:event_Txt_NombreKeyPressed

    private void Txt_Id_ProdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Id_ProdKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_Txt_Id_ProdKeyPressed

    private void Spn_Precio_CompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_Precio_CompraKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_Spn_Precio_CompraKeyPressed

    private void Spn_Porcentaje_VentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_Porcentaje_VentaKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_Spn_Porcentaje_VentaKeyPressed

    private void Spn_CantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_CantidadKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_Spn_CantidadKeyPressed

    private void Spn_Precio_CompraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_Precio_CompraKeyReleased
        this.objExcepciones.validarExpresionSpinner(Spn_Precio_Compra, "^(\\d{1,7})$");
    }//GEN-LAST:event_Spn_Precio_CompraKeyReleased

    private void Spn_Porcentaje_VentaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_Porcentaje_VentaKeyReleased
        this.objExcepciones.validarExpresionSpinner(Spn_Porcentaje_Venta, "^(\\d{1,3})$");
    }//GEN-LAST:event_Spn_Porcentaje_VentaKeyReleased

    private void Spn_CantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Spn_CantidadKeyReleased
        this.objExcepciones.validarExpresionSpinner(Spn_Cantidad, "^(\\d{1,3})$");
    }//GEN-LAST:event_Spn_CantidadKeyReleased

    private void Txt_Id_ProdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_Id_ProdKeyReleased
        this.objExcepciones.validarExpresionTxt(Txt_Id_Prod, "^(\\d{2,15})$");
    }//GEN-LAST:event_Txt_Id_ProdKeyReleased

    private void Txt_NombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_NombreKeyReleased
        this.objExcepciones.validarExpresionTxt(Txt_Nombre, "[a-zA-ZñÑ\\s]{2,40}");
    }//GEN-LAST:event_Txt_NombreKeyReleased

    private void Txt_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_MarcaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            JifListar_Productos jifListar_Productos = new JifListar_Productos();
            this.objExcepciones.controlaInstancia(jifListar_Productos, this.getDesktopPane());
            jifListar_Productos.setVisible(true);
            jifListar_Productos.setClosable(true);
            this.setClosed(true);
            this.setVisible(false);

        } catch (PropertyVetoException ex) {
            Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Btn_AddCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddCategoriaActionPerformed
        try {
            if (!this.Txt_Categoria.getText().equals("") && !this.Txt_Categoria.getForeground().equals(Color.red)) {
                if ((this.objCategoria == null) || this.Btn_AddCategoria.getText().equalsIgnoreCase("Agregar")) {
                    if (this.objDataCategoria.addNewCategory(new DTO_Categoria(this.Txt_Categoria.getText().toUpperCase(), true))) {
                        JOptionPane.showMessageDialog(this, "La categoria " + this.Txt_Categoria.getText() + " fue añadida correctamente.", "Agregar categroria", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    this.objCategoria.setNombre(this.Txt_Categoria.getText().toUpperCase());
                    if (this.objDataCategoria.modificarCategoria(objCategoria)) {
                        JOptionPane.showMessageDialog(this, "¡ Categoría modificada correctamente !.", "Modificar categoría", JOptionPane.INFORMATION_MESSAGE);
                        this.Btn_AddCategoria.setText("Agregar");
                    }
                }
                this.Txt_Categoria.setText("");
                this.fillCategoriesAndMarcasList();
            } else {
                JOptionPane.showMessageDialog(this, "Lo siento, no es permitido dejar espacios en blanco o erroneos.", "Agregar categroria", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_AddCategoriaActionPerformed

    private void Txt_CategoriaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_CategoriaKeyPressed
        this.objExcepciones.validarLetra(evt);
    }//GEN-LAST:event_Txt_CategoriaKeyPressed

    private void Txt_CategoriaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_CategoriaKeyReleased
        this.objExcepciones.validarExpresionTxt(this.Txt_Categoria, "[a-zA-ZñÑ\\s]{2,20}");
    }//GEN-LAST:event_Txt_CategoriaKeyReleased

    private void Btn_EliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarCatActionPerformed
        int fila_seleccionada = this.Tbl_Categoria.getSelectedRow();
        if (fila_seleccionada >= 0) {
            int resp = JOptionPane.showConfirmDialog(this,
                    "¿Esta seguro de eliminar la categoría " + this.tblCatModel.getValueAt(fila_seleccionada, 1) + "\n"
                    + "Recuerde que esta opción es ireversible.",
                    "Eliminar categoria", JOptionPane.WARNING_MESSAGE);
            if (resp == JOptionPane.YES_OPTION) {
                try {
                    if (this.objDataCategoria.modificarEstadoCategoria((int) this.tblCatModel.getValueAt(fila_seleccionada, 0), !this.current_state)) {
                        JOptionPane.showMessageDialog(this, "¡ Categoría eliminada correctamente !.", "Eliminar categoria", JOptionPane.INFORMATION_MESSAGE);
                        this.tblCatModel.removeRow(fila_seleccionada);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un elemento de la lista.", "¡Adventencia!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EliminarCatActionPerformed

    private void Btn_ModificarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarCatActionPerformed
        int fila_seleccionada = this.Tbl_Categoria.getSelectedRow();

        if (fila_seleccionada >= 0) {

            try {
                this.objCategoria = this.objDataCategoria.getSingleCategory((int) this.tblCatModel.getValueAt(fila_seleccionada, 0), this.current_state);
                this.Txt_Categoria.setText(objCategoria.getNombre());
                this.Btn_AddCategoria.setText("Modificar");
            } catch (SQLException ex) {
                Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un elemento de la lista.", "¡Adventencia!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_ModificarCatActionPerformed

    private void TBN_EstadoCatItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TBN_EstadoCatItemStateChanged
        if (this.TBN_EstadoCat.isSelected()) {
            this.TBN_EstadoCat.setText("Inactivos");
            this.Btn_EliminarCat.setText("Reestablecer");
            this.Btn_EliminarMarca.setText("Reestablecer");
            this.current_state = false;
        } else {
            this.TBN_EstadoCat.setText("Activos");
            this.Btn_EliminarCat.setText("Eliminar");
            this.Btn_EliminarMarca.setText("Eliminar");
            this.current_state = true;
        }
        this.fillCategoriesAndMarcasList();
    }//GEN-LAST:event_TBN_EstadoCatItemStateChanged

    private void Btn_EditMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EditMarcaActionPerformed
        int fila_seleccionada = this.Tbl_Marca.getSelectedRow();

        if (fila_seleccionada >= 0) {

            try {
                this.objMarca = this.objDataMarca.getSingleMarca((int) this.tblMarcModel.getValueAt(fila_seleccionada, 0), this.current_state);
                this.fillMarcasData(objMarca);
                this.Cbx_MarcaCat.setEnabled(false);
                this.Btn_AddMarca.setText("Modificar");
            } catch (SQLException ex) {
                Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un elemento de la lista.", "¡Adventencia!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EditMarcaActionPerformed

    private void Btn_AddMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AddMarcaActionPerformed
        try {
            if (!this.Txt_Marca.getText().trim().equals("") && !this.Txt_Marca.getForeground().equals(Color.red)) {
                if ((this.objMarca == null) || this.Btn_AddMarca.getText().equalsIgnoreCase("Agregar")) {
                    if (this.objDataCategoria_Marca.addNewCategoria_Marca(this.getCategoryById(this.Cbx_MarcaCat),
                            this.objDataMarca.addNewMarca(new DTO_Marca(this.getProveedorById(), this.Txt_Marca.getText().toUpperCase())))) {
                        JOptionPane.showMessageDialog(this, "La marca " + this.Txt_Marca.getText() + " fue añadida correctamente.", "Agregar marca", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    //this.fillMarcasData(objMarca);
                    this.objMarca.setNombre(this.Txt_Marca.getText().toUpperCase());
                    this.objMarca.setProveedor(this.getProveedorById());
                    if (this.objDataMarca.modificarMarca(objMarca)) {
                        JOptionPane.showMessageDialog(this, "¡ Marca modificada correctamente !.", "Modificar marca", JOptionPane.INFORMATION_MESSAGE);
                        this.Btn_AddCategoria.setText("Agregar");
                        this.Cbx_MarcaCat.setEnabled(true);
                    }
                }
                this.Txt_Marca.setText("");
                this.fillCategoriesAndMarcasList();
            } else {
                JOptionPane.showMessageDialog(this, "Lo siento, no es permitido dejar espacios en blanco o erroneos.", "Agregar marca", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Btn_AddMarcaActionPerformed

    private void Txt_MarcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_MarcaKeyPressed
        this.objExcepciones.validarLetra(evt);
    }//GEN-LAST:event_Txt_MarcaKeyPressed

    private void Txt_MarcaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_MarcaKeyReleased
        this.objExcepciones.validarExpresionTxt(this.Txt_Marca, "[a-zA-ZñÑ\\s]{3,35}");
    }//GEN-LAST:event_Txt_MarcaKeyReleased

    private void Btn_EliminarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarMarcaActionPerformed
        int fila_seleccionada = this.Tbl_Marca.getSelectedRow();
        if (fila_seleccionada >= 0) {
            int resp = JOptionPane.showConfirmDialog(this,
                    "¿Esta seguro de eliminar la marca " + this.tblMarcModel.getValueAt(fila_seleccionada, 1) + "\n"
                    + "Recuerde que esta opción es ireversible.",
                    "Eliminar marca", JOptionPane.WARNING_MESSAGE);
            if (resp == JOptionPane.YES_OPTION) {
                try {
                    if (this.objDataMarca.modificarEstadoMarca((int) this.tblMarcModel.getValueAt(fila_seleccionada, 0), !this.current_state)) {
                        JOptionPane.showMessageDialog(this, "¡ Marca eliminada correctamente !.", "Eliminar marca", JOptionPane.INFORMATION_MESSAGE);
                        this.tblMarcModel.removeRow(fila_seleccionada);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(JifProducto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un elemento de la lista.", "¡Adventencia!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Btn_EliminarMarcaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_AddCategoria;
    private javax.swing.JButton Btn_AddMarca;
    private javax.swing.JButton Btn_EditMarca;
    private javax.swing.JButton Btn_EliminarCat;
    private javax.swing.JButton Btn_EliminarMarca;
    private javax.swing.JButton Btn_ModificarCat;
    private javax.swing.JComboBox<String> Cbx_Cat;
    private javax.swing.JComboBox<String> Cbx_Marca;
    private javax.swing.JComboBox<String> Cbx_MarcaCat;
    private javax.swing.JComboBox<String> Cbx_Proveedor;
    private javax.swing.JTabbedPane JtpProducto;
    private javax.swing.JLabel Lbl_CatTitulo;
    private javax.swing.JLabel Lbl_TituloMarca;
    private javax.swing.JSpinner Spn_Cantidad;
    private javax.swing.JSpinner Spn_Porcentaje_Venta;
    private javax.swing.JSpinner Spn_Precio_Compra;
    private javax.swing.JToggleButton TBN_EstadoCat;
    private javax.swing.JTable Tbl_Categoria;
    private javax.swing.JTable Tbl_Marca;
    private javax.swing.JTextField Txt_Categoria;
    private javax.swing.JTextField Txt_Id_Prod;
    private javax.swing.JTextField Txt_Marca;
    private javax.swing.JTextField Txt_Nombre;
    private javax.swing.JButton btn_RegistrarProd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

    private void setComponentsCofig() throws SQLException {
        this.objExcepciones = new Excepciones();
        this.objDataCategoria = new DAO_Categoria();
        this.objDataMarca = new DAO_Marca();
        this.objDataProducto = new DAO_Producto();
        this.objDataProveedor = new DAO_Persona();
        this.objDataCategoria_Marca = new DAO_Categoria_Marca();
        this.objProveedor = new DTO_Persona();
        this.objMarca = null;
        this.objCategoria = null;
        this.Spn_Precio_Compra.setModel(new SpinnerNumberModel(0, 0, 1000000, 1));
        this.Spn_Porcentaje_Venta.setModel(new SpinnerNumberModel(0, 0, 100, 1));
        this.Spn_Cantidad.setModel(new SpinnerNumberModel(0, 0, 10000, 1));
        this.current_state = true;

        this.tblCatModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        this.tblMarcModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };

        this.tblCatModel.addColumn("Cod. Categoría");
        this.tblCatModel.addColumn("Nombre");
        this.Tbl_Categoria.setModel(tblCatModel);

        this.tblMarcModel.addColumn("Cod. Marca");
        this.tblMarcModel.addColumn("Nombre");
        this.tblMarcModel.addColumn("Proveedor");
        this.Tbl_Marca.setModel(tblMarcModel);

        this.fillCategoriesAndMarcasList();
    }

    private DTO_Categoria getCategoryById(JComboBox Cbx) throws SQLException {
        String item = Cbx.getSelectedItem().toString();
        int id_category = Integer.parseInt(item.split("-")[0]);
        return this.objDataCategoria.getSingleCategory(id_category, true);
    }

    private DTO_Marca getMarcaById() throws SQLException {
        String item = this.Cbx_Marca.getSelectedItem().toString();
        int id_marca = Integer.parseInt(item.split("-")[0]);
        return this.objDataMarca.getSingleMarca(id_marca, true);
    }

    private DTO_Persona getProveedorById() throws SQLException {
        String item = this.Cbx_Proveedor.getSelectedItem().toString();
        String id_persona = item.split("-")[0];
        return this.objDataProveedor.getSinglePersona(id_persona, true);
    }

    private void cleanAllInputs() {
        this.Txt_Id_Prod.setText("");
        this.Txt_Id_Prod.setEnabled(true);
        this.Txt_Nombre.setText("");
        this.Spn_Precio_Compra.setModel(new SpinnerNumberModel(0, 0, 1000000, 1));
        this.Spn_Porcentaje_Venta.setModel(new SpinnerNumberModel(0, 0, 100, 1));
        this.Spn_Cantidad.setModel(new SpinnerNumberModel(0, 0, 10000, 1));
    }

    private void fillProductData(DTO_Producto objProducto) {
        this.Txt_Id_Prod.setText(objProducto.getId_Producto());
        this.Cbx_Marca.setSelectedItem(objProducto.getMarca().getId_Marca() + "- "
                + objProducto.getMarca().getNombre() + " de "
                + objProducto.getMarca().getProveedor().getNombre());
        this.Cbx_Proveedor.setSelectedItem(objProducto.getCategoria().getId_Categoria() + "- "
                + objProducto.getCategoria().getNombre());
        this.Txt_Nombre.setText(objProducto.getNombre());
        this.Spn_Precio_Compra.setValue(objProducto.getPrecio_Compra());
        this.Spn_Porcentaje_Venta.setValue(objProducto.getPorcentaje_Venta() * 100);
        this.Spn_Cantidad.setValue(objProducto.getCantidad());
        this.btn_RegistrarProd.setText("Modificar producto");
        this.Txt_Id_Prod.setEnabled(false);
    }

    private void fillMarcasData(DTO_Marca objMarca) {
        this.Txt_Marca.setText(objMarca.getNombre());
        //proveedor.getDNI() + "- " + proveedor.getNombre()
        this.Cbx_Proveedor.setSelectedItem(objMarca.getProveedor().getDNI() + "- " + objMarca.getProveedor().getNombre());
        //category.getId_Categoria() + "- " + category.getNombre()
        //this.Cbx_MarcaCat.setSelectedItem(objMarca);
    }

    private void fillCategoriesAndMarcasList() {
        this.objExcepciones.limpiarTabla(this.Tbl_Categoria, this.tblCatModel);

        this.objExcepciones.limpiarTabla(this.Tbl_Marca, this.tblMarcModel);

        this.Cbx_Marca.removeAllItems();
        this.Cbx_Cat.removeAllItems();

        this.Cbx_Proveedor.removeAllItems();
        this.Cbx_MarcaCat.removeAllItems();

        try {
            this.objDataCategoria.getAllCategories(current_state).
                    forEach(category
                            -> {
                        this.Cbx_Cat.addItem(category.getId_Categoria() + "- " + category.getNombre());
                        this.Cbx_MarcaCat.addItem(category.getId_Categoria() + "- " + category.getNombre());
                        this.tblCatModel.addRow(new Object[]{
                            category.getId_Categoria(),
                            category.getNombre()
                        });
                    });

            this.objDataMarca.getAllMarcas(current_state).
                    forEach(marca
                            -> {
                        this.Cbx_Marca.addItem(marca.getId_Marca() + "- " + marca.getNombre() + " de " + marca.getProveedor().getNombre());
                        this.tblMarcModel.addRow(new Object[]{
                            marca.getId_Marca(),
                            marca.getNombre(),
                            marca.getProveedor().getNombre()
                        });
                    }
                    );

            this.objDataProveedor.getAllProveedores(this.current_state).
                    forEach(proveedor -> {
                        this.Cbx_Proveedor.addItem(proveedor.getDNI() + "- " + proveedor.getNombre());
                    });

        } catch (SQLException ex) {
            System.out.println("Error en la Base de datos: " + ex.getMessage());
        }
    }

}
