/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.DAO_Persona;
import Controlador.DAO_Rol;
import Modelo.DTO_Persona;
import Modelo.DTO_Rol;
import Tools.Excepciones;
import Tools.TimestampCertificates;
import java.security.Timestamp;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MARCELO RUENES
 */
public class JifPersona extends javax.swing.JInternalFrame {

    private Excepciones objExcepciones;
    private DAO_Rol objDataRol;
    private DAO_Persona objDataPersona;

    /**
     * Creates new form JifEmpleado
     */
    public JifPersona() {
        initComponents();
        try {
            fillCbxRol();
        } catch (SQLException ex) {
            Logger.getLogger(JifPersona.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtIdEmp = new javax.swing.JTextField();
        TxtNombreEmp = new javax.swing.JTextField();
        TxtTelEmp = new javax.swing.JTextField();
        TxtDirEmp = new javax.swing.JTextField();
        BtnAgregarEmpleado = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Cbx_Rol = new javax.swing.JComboBox<>();
        DchFechaNac = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("AGREGAR PERSONA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identificación:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Fecha de nacimiento:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("telefono:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Direcciión:");

        TxtIdEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtIdEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtIdEmpActionPerformed(evt);
            }
        });
        TxtIdEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtIdEmpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtIdEmpKeyReleased(evt);
            }
        });

        TxtNombreEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtNombreEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreEmpActionPerformed(evt);
            }
        });
        TxtNombreEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtNombreEmpKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtNombreEmpKeyReleased(evt);
            }
        });

        TxtTelEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TxtTelEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtTelEmpActionPerformed(evt);
            }
        });

        TxtDirEmp.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        BtnAgregarEmpleado.setText("AGREGAR");
        BtnAgregarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarEmpleadoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ROL:");

        Cbx_Rol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cbx_RolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtTelEmp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtIdEmp, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtNombreEmp)
                                    .addComponent(Cbx_Rol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtDirEmp)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                                .addComponent(DchFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(BtnAgregarEmpleado)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtIdEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TxtNombreEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cbx_Rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(DchFechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtTelEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TxtDirEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BtnAgregarEmpleado)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtNombreEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreEmpActionPerformed

    private void TxtTelEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtTelEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtTelEmpActionPerformed

    private void BtnAgregarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarEmpleadoActionPerformed
        try {
            //DAO_Persona objDataPersona = new DAO_Persona();
            TimestampCertificates tc = new TimestampCertificates();
            if (this.objExcepciones.validarCamposPersona(TxtIdEmp, TxtNombreEmp, this.DchFechaNac, TxtTelEmp, TxtDirEmp)
                    && this.objExcepciones.validarCamposErrPersona(TxtIdEmp, TxtNombreEmp, this.DchFechaNac, TxtTelEmp, TxtDirEmp)) {

                if (this.TxtIdEmp.isEnabled()) {
                    if (this.objDataPersona.registrarNuevaPersona(new DTO_Persona(this.TxtIdEmp.getText(),
                            this.TxtNombreEmp.getText().toUpperCase(),
                            this.TxtTelEmp.getText(),
                            this.TxtDirEmp.getText(),
                            new Timestamp(new Date(), tc.getCertPath()),
                            this.DchFechaNac.getDate(),
                            true
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡La persona " + this.TxtNombreEmp.getText().toUpperCase() + " se ha registrado con éxito!", "Registro de producto", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Registro de persona", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    if (this.objDataPersona.modificarPersona(new DTO_Persona(this.TxtIdEmp.getText(),
                            this.TxtNombreEmp.getText().toUpperCase(),
                            this.TxtTelEmp.getText(),
                            this.TxtDirEmp.getText(),
                            new Timestamp(new Date(), tc.getCertPath()),
                            this.DchFechaNac.getDate()
                    ))) {
                        JOptionPane.showMessageDialog(this, "¡La persona " + this.TxtNombreEmp.getText().toUpperCase() + " se ha modificado con éxito!", "Modificación de persona", JOptionPane.INFORMATION_MESSAGE);
                        this.cleanAllInputs();
                    } else {
                        JOptionPane.showMessageDialog(this, "Algo salió mal", "Modificación de persona", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No puede dejar campos vacios o erroneos", "Registro de persona", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            if (ex.getErrorCode() == 0) {
                System.out.println("Persona: " + ex.getMessage());
                int res = JOptionPane.showConfirmDialog(this, "Esta persona ya se encuentra registrado\n"
                        + "¿Desea editarlo?", "Registro de persona", JOptionPane.ERROR_MESSAGE);
                if (res == JOptionPane.YES_OPTION) {
                    try {
                        this.fillData(this.objDataPersona.getSinglePersona(this.TxtIdEmp.getText(), true));
                    } catch (SQLException exSP) {
                        Logger.getLogger(JifPersona.class.getName()).log(Level.SEVERE, null, exSP);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Registro de persona", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_BtnAgregarEmpleadoActionPerformed

    private void Cbx_RolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cbx_RolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cbx_RolActionPerformed

    private void TxtIdEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtIdEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtIdEmpActionPerformed

    private void TxtIdEmpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdEmpKeyPressed
        this.objExcepciones.validarNum(evt);
    }//GEN-LAST:event_TxtIdEmpKeyPressed

    private void TxtIdEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtIdEmpKeyReleased
        this.objExcepciones.validarExpresionTxt(this.TxtIdEmp, "^(\\d{2,11})$");
    }//GEN-LAST:event_TxtIdEmpKeyReleased

    private void TxtNombreEmpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreEmpKeyPressed
        this.objExcepciones.validarLetra(evt);
    }//GEN-LAST:event_TxtNombreEmpKeyPressed

    private void TxtNombreEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtNombreEmpKeyReleased
        this.objExcepciones.validarExpresionTxt(this.TxtNombreEmp, "[a-zA-ZñÑ\\s]{2,40}");
    }//GEN-LAST:event_TxtNombreEmpKeyReleased

    private DTO_Rol getRolById() throws SQLException {
        String item = this.Cbx_Rol.getSelectedItem().toString();
        int id_Rol = Integer.parseInt(item.split("-")[0]);
        return this.objDataRol.getSingleRol(id_Rol, true);
    }

    private void cleanAllInputs() {
        this.TxtIdEmp.setText("");
        this.TxtIdEmp.setEnabled(true);
        this.TxtNombreEmp.setText("");
        this.DchFechaNac.setDateFormatString("");
        this.TxtTelEmp.setText("");
        this.TxtDirEmp.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregarEmpleado;
    private javax.swing.JComboBox<String> Cbx_Rol;
    private com.toedter.calendar.JDateChooser DchFechaNac;
    private javax.swing.JTextField TxtDirEmp;
    private javax.swing.JTextField TxtIdEmp;
    private javax.swing.JTextField TxtNombreEmp;
    private javax.swing.JTextField TxtTelEmp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables

    private void fillData(DTO_Persona objPersona) {
        this.TxtIdEmp.setText(objPersona.getDNI());
        this.TxtNombreEmp.setText(objPersona.getNombre());
        //this.Cbx_Rol.setSelectedItem(objPersona.getRol().getId_Rol() + "- "
        //      + objPersona.getRol().getNombre_Rol());
        this.TxtTelEmp.setText(objPersona.getTelefono());
        this.TxtDirEmp.setText(objPersona.getDireccion());
        this.DchFechaNac.setDate(objPersona.getFecha_Nacimiento());
        this.BtnAgregarEmpleado.setText("Modificar persona");

    }

    private void fillCbxRol() throws SQLException {
        this.objExcepciones = new Excepciones();
        this.objDataRol = new DAO_Rol();
        this.objDataPersona = new DAO_Persona();
        this.objDataRol.getAllRoles(true).forEach(Rol -> {
            this.Cbx_Rol.addItem(Rol.getId_Rol() + "- " + Rol.getNombre_Rol());
        });
    }

}
