/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.DTO_Persona_Rol;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class JifTestSession extends javax.swing.JInternalFrame {

    /**
     * Creates new form JifTestSession
     *
     * @param ObjPersona_Rol
     */
    public JifTestSession(DTO_Persona_Rol ObjPersona_Rol) {
        
        if (ObjPersona_Rol != null) {
            initComponents();
            System.out.println("Persona: " + ObjPersona_Rol.getPersona().getNombre());
            this.txtNombre.setText(ObjPersona_Rol.getPersona().getNombre());
        }else{
            JOptionPane.showMessageDialog(this, "No se ha logueado aún.");
        }

    }

    public JifTestSession() {
        initComponents();
        System.out.println("No se ha logueado");
        this.txtNombre.setText("Requiere de logueo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();

        jLabel1.setText("Nombre: ");

        txtNombre.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel txtNombre;
    // End of variables declaration//GEN-END:variables
}
